name: check append
on:
  workflow_dispatch:
jobs:
  build:
    name: check append
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Create Release Version
        run: |
          c="$git tag -l"
          echo "$c"
